<?php
/**
 * Seeded content cookbook fixture.
 *
 * Creates a compact editorial site shape for plugins or themes that need real
 * posts, pages, terms, and non-admin users without copying parent-site data.
 *
 * Output: JSON with seeded object IDs plus frontend and admin preview URLs.
 */

require_once ABSPATH . 'wp-admin/includes/plugin.php';

// Activate the mounted plugin under test when present. The default cookbook
// recipe points at examples/simple-plugin so the recipe runs out of the box.
$plugin_under_test = null;
foreach ( get_plugins( '/plugin-under-test' ) as $plugin_file => $plugin_data ) {
	if ( ! empty( $plugin_data['Name'] ) ) {
		$plugin_under_test = 'plugin-under-test/' . $plugin_file;
		break;
	}
}

if ( $plugin_under_test && ! is_plugin_active( $plugin_under_test ) ) {
	$activation_result = activate_plugin( $plugin_under_test );
	if ( is_wp_error( $activation_result ) ) {
		throw new RuntimeException( $activation_result->get_error_message() );
	}
}

$editor_id = username_exists( 'cookbook-editor' );
if ( ! $editor_id ) {
	$editor_id = wp_insert_user( array(
		'user_login'   => 'cookbook-editor',
		'user_pass'    => wp_generate_password( 24, true, true ),
		'user_email'   => 'cookbook-editor@example.test',
		'display_name' => 'Cookbook Editor',
		'role'         => 'editor',
	) );
}

if ( is_wp_error( $editor_id ) || ! $editor_id ) {
	throw new RuntimeException( 'Failed to create editor user' );
}

$author_id = username_exists( 'cookbook-author' );
if ( ! $author_id ) {
	$author_id = wp_insert_user( array(
		'user_login'   => 'cookbook-author',
		'user_pass'    => wp_generate_password( 24, true, true ),
		'user_email'   => 'cookbook-author@example.test',
		'display_name' => 'Cookbook Author',
		'role'         => 'author',
	) );
}

if ( is_wp_error( $author_id ) || ! $author_id ) {
	throw new RuntimeException( 'Failed to create author user' );
}

$category_ids = array();
foreach ( array( 'Field Notes', 'Announcements' ) as $category_name ) {
	$term = term_exists( $category_name, 'category' );
	if ( ! $term ) {
		$term = wp_insert_term( $category_name, 'category' );
	}

	if ( is_wp_error( $term ) || empty( $term['term_id'] ) ) {
		throw new RuntimeException( 'Failed to create category: ' . $category_name );
	}

	$category_ids[ $category_name ] = (int) $term['term_id'];
}

$tag_ids = array();
foreach ( array( 'sandbox', 'fixture', 'longform' ) as $tag_name ) {
	$term = term_exists( $tag_name, 'post_tag' );
	if ( ! $term ) {
		$term = wp_insert_term( $tag_name, 'post_tag' );
	}

	if ( is_wp_error( $term ) || empty( $term['term_id'] ) ) {
		throw new RuntimeException( 'Failed to create tag: ' . $tag_name );
	}

	$tag_ids[ $tag_name ] = (int) $term['term_id'];
}

$home_page_id = wp_insert_post( array(
	'post_title'   => 'Seeded Content Home',
	'post_content' => '<!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Seeded content fixture</h1><!-- /wp:heading --><!-- wp:paragraph --><p>This page is generated by the WP Codebox seeded-content cookbook recipe. Use it to exercise plugins and themes against realistic pages, posts, terms, and users.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/blog/">Read the seeded posts</a></div><!-- /wp:button --></div><!-- /wp:buttons -->',
	'post_status'  => 'publish',
	'post_type'    => 'page',
	'post_author'  => (int) $editor_id,
) );

if ( is_wp_error( $home_page_id ) || ! $home_page_id ) {
	throw new RuntimeException( 'Failed to create home page' );
}

$blog_page_id = wp_insert_post( array(
	'post_title'   => 'Blog',
	'post_content' => '<!-- wp:paragraph --><p>Posts page for seeded content fixture.</p><!-- /wp:paragraph -->',
	'post_status'  => 'publish',
	'post_type'    => 'page',
	'post_author'  => (int) $editor_id,
	'post_name'    => 'blog',
) );

if ( is_wp_error( $blog_page_id ) || ! $blog_page_id ) {
	throw new RuntimeException( 'Failed to create blog page' );
}

$about_page_id = wp_insert_post( array(
	'post_title'   => 'About the Fixture',
	'post_content' => '<!-- wp:paragraph --><p>A stable page with normal paragraph content, useful for checking menus, templates, and page-specific plugin behavior.</p><!-- /wp:paragraph -->',
	'post_status'  => 'publish',
	'post_type'    => 'page',
	'post_author'  => (int) $editor_id,
	'post_parent'  => (int) $home_page_id,
) );

if ( is_wp_error( $about_page_id ) || ! $about_page_id ) {
	throw new RuntimeException( 'Failed to create about page' );
}

$post_specs = array(
	array(
		'title'      => 'Field report with blocks and lists',
		'content'    => '<!-- wp:paragraph --><p>This seeded post includes paragraphs, a list, and a quote so block-aware plugins have more than empty content to inspect.</p><!-- /wp:paragraph --><!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li>Alpha content shape</li><!-- /wp:list-item --><!-- wp:list-item --><li>Beta content shape</li><!-- /wp:list-item --></ul><!-- /wp:list --><!-- wp:quote --><blockquote class="wp-block-quote"><!-- wp:paragraph --><p>Fixture data should be explicit, boring, and safe to replay.</p><!-- /wp:paragraph --></blockquote><!-- /wp:quote -->',
		'category'   => 'Field Notes',
		'tags'       => array( 'sandbox', 'fixture', 'longform' ),
		'post_name'  => 'field-report-with-blocks-and-lists',
		'post_date'  => '2026-05-01 10:00:00',
	),
	array(
		'title'      => 'Announcement with short copy',
		'content'    => '<!-- wp:paragraph --><p>A shorter announcement-style post for archive and excerpt testing.</p><!-- /wp:paragraph -->',
		'category'   => 'Announcements',
		'tags'       => array( 'sandbox' ),
		'post_name'  => 'announcement-with-short-copy',
		'post_date'  => '2026-05-02 11:30:00',
	),
	array(
		'title'      => 'Draft content for editor-only surfaces',
		'content'    => '<!-- wp:paragraph --><p>This draft gives admin and editor screens a non-public content state to render.</p><!-- /wp:paragraph -->',
		'category'   => 'Field Notes',
		'tags'       => array( 'fixture' ),
		'post_name'  => 'draft-content-for-editor-only-surfaces',
		'post_date'  => '2026-05-03 12:00:00',
		'post_status' => 'draft',
	),
);

$post_ids = array();
foreach ( $post_specs as $spec ) {
	$post_id = wp_insert_post( array(
		'post_title'   => $spec['title'],
		'post_content' => $spec['content'],
		'post_status'  => $spec['post_status'] ?? 'publish',
		'post_type'    => 'post',
		'post_author'  => (int) $author_id,
		'post_name'    => $spec['post_name'],
		'post_date'    => $spec['post_date'],
	) );

	if ( is_wp_error( $post_id ) || ! $post_id ) {
		throw new RuntimeException( 'Failed to create post: ' . $spec['title'] );
	}

	wp_set_post_categories( $post_id, array( $category_ids[ $spec['category'] ] ) );
	wp_set_post_tags( $post_id, $spec['tags'] );
	$post_ids[] = (int) $post_id;
}

update_option( 'show_on_front', 'page' );
update_option( 'page_on_front', (int) $home_page_id );
update_option( 'page_for_posts', (int) $blog_page_id );
update_option( 'permalink_structure', '/%postname%/' );

global $wp_rewrite;
$wp_rewrite->init();
$wp_rewrite->flush_rules( false );

wp_set_auth_cookie( 1, true );

echo wp_json_encode( array(
	'users' => array(
		'editor_id' => (int) $editor_id,
		'author_id' => (int) $author_id,
	),
	'terms' => array(
		'categories' => $category_ids,
		'tags'       => $tag_ids,
	),
	'pages' => array(
		'home_id'  => (int) $home_page_id,
		'blog_id'  => (int) $blog_page_id,
		'about_id' => (int) $about_page_id,
	),
	'posts' => $post_ids,
	'preview_urls' => array(
		'home'          => get_permalink( $home_page_id ),
		'blog'          => get_permalink( $blog_page_id ),
		'first_post'    => get_permalink( $post_ids[0] ),
		'category'      => get_category_link( $category_ids['Field Notes'] ),
		'author_archive' => get_author_posts_url( (int) $author_id ),
	),
	'admin_urls' => array(
		'posts' => admin_url( 'edit.php' ),
		'pages' => admin_url( 'edit.php?post_type=page' ),
		'users' => admin_url( 'users.php' ),
	),
	'plugin_under_test' => $plugin_under_test ? is_plugin_active( $plugin_under_test ) : false,
	'plugin_file'       => $plugin_under_test,
), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
echo "\n";
