import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"

const abilitiesPhp = await readFile("packages/wordpress-plugin/src/class-wp-codebox-abilities.php", "utf8")
const schemasPhp = await readFile("packages/wordpress-plugin/src/trait-wp-codebox-abilities-schemas.php", "utf8")
const executionPhp = await readFile("packages/wordpress-plugin/src/trait-wp-codebox-abilities-execution.php", "utf8")

for (const ability of ["wp-codebox/run-wordpress-workload", "wp-codebox/run-fuzz-suite"]) {
  assert.match(abilitiesPhp, new RegExp(`wp_register_ability\\(\\s*'${ability}'`), `${ability} must be registered`)
  assert.match(abilitiesPhp, new RegExp(`'canonical_ability'\\s*=>\\s*'${ability}'`), `${ability} must mark its canonical id`)
}

assert.match(abilitiesPhp, /'wp-codebox\/run-wordpress-workload'[\s\S]{0,700}'execute_callback'\s*=>\s*array\(\s*self::class,\s*'run_wordpress_workload'\s*\)/, "WordPress workload is implemented by the public ability")
assert.doesNotMatch(abilitiesPhp, /'wp-codebox\/run-wordpress-workload'[\s\S]{0,700}'safe_stub'\s*=>\s*true/, "WordPress workload is implemented and must not be marked as a safe stub")
assert.doesNotMatch(abilitiesPhp, /'wp-codebox\/run-fuzz-suite'[\s\S]{0,700}'safe_stub'\s*=>\s*true/, "Fuzz suite is implemented and must not be marked as a safe stub")

assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/wordpress-workload-run\/v1'/)
assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/wordpress-workload-run-result\/v1'/)
assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/fuzz-suite\/v1'/)
assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/fuzz-suite-result\/v1'/)
assert.match(schemasPhp, /'kind'\s*=>\s*array\( 'type' => 'string', 'enum' => array\( 'ability', 'command', 'http', 'rest', 'runtime', 'runtime-action' \) \)/)
assert.doesNotMatch(schemasPhp, /include_raw_browser_session/, "public browser session input schema must not expose raw browser session escape hatches")
assert.match(schemasPhp, /'required'\s*=>\s*array\( 'task', 'target_id' \)/, "runtime task requests must require explicit target_id")
const runtimeTaskSchema = schemasPhp.slice(schemasPhp.indexOf("private static function runtime_task_request_schema"), schemasPhp.indexOf("private static function runtime_task_result_schema"))
assert.doesNotMatch(runtimeTaskSchema, /'executor_id'\s*=>|\s'executor'\s*=>|\s'target'\s*=>/, "runtime task public schema must not advertise implicit target aliases")

assert.match(executionPhp, /function run_wordpress_workload\( array \$input \)/)
assert.match(executionPhp, /function run_fuzz_suite\( array \$input \)/)
assert.match(executionPhp, /unsafe_execution_fields/)
assert.match(executionPhp, /collect_unsafe_execution_fields/)
assert.match(executionPhp, /'code', 'php', 'php_code', 'raw_code', 'eval', 'shell'/)
assert.match(executionPhp, /array\( 'command' \)/)
assert.match(executionPhp, /new WP_Codebox_WordPress_Workload_Runner\(\)/)
assert.match(executionPhp, /execute_fuzz_suite_case/)
assert.match(executionPhp, /wordpress\.rest-request/)
assert.match(executionPhp, /wordpress\.http-request/)
assert.match(executionPhp, /fuzz_suite_runtime_action_step/)
assert.match(executionPhp, /wordpress\.wp-cli/)
assert.match(executionPhp, /wordpress\.browser-actions/)
assert.match(executionPhp, /wordpress\.browser-probe/)
assert.match(executionPhp, /wordpress\.editor-open/)
assert.match(executionPhp, /wordpress\.admin-page-load/)
assert.match(executionPhp, /wordpress\.frontend-page-load/)
assert.match(executionPhp, /function fuzz_suite_supported_runner_capabilities\(\)/)
assert.match(executionPhp, /function fuzz_suite_runtime_backed_runner_capabilities_contract/)
assert.match(abilitiesPhp, /Run safe PHP in-process WordPress fuzz-suite cases/)
assert.match(abilitiesPhp, /Runtime-backed execution is available through the public wp-codebox CLI or TypeScript facade/)
assert.match(executionPhp, /runtime-action:db_operation/)
assert.match(executionPhp, /wordpress\.db-operation/)
assert.match(executionPhp, /executeWordPressFuzzSuite/)
assert.match(executionPhp, /wp-codebox run-fuzz-suite --runner-mode=runtime-backed/)
assert.match(executionPhp, /'ability_execution_mode'\s*=>\s*'php-in-process-only'/)
assert.match(executionPhp, /'supported_by_this_ability'\s*=>\s*false/)
assert.match(abilitiesPhp, /'supported_runner_capabilities'\s*=>\s*self::fuzz_suite_supported_runner_capabilities\(\)/)
assert.match(abilitiesPhp, /'runtime_backed_execution'\s*=>\s*self::fuzz_suite_runtime_backed_execution_contract\(\)/)
assert.match(executionPhp, /wordpress\.ensure-plugin-active/)
assert.match(executionPhp, /'commands'[\s\S]{0,900}wordpress\.ensure-plugin-active/)
assert.match(executionPhp, /'commands'[\s\S]{0,900}wordpress\.plugin-state/)
assert.match(executionPhp, /WP_CODEBOX_FUZZ_WORKLOAD_ROOT/)
assert.doesNotMatch(executionPhp, /wp_codebox_fuzz_suite_runner_unavailable/)

assert.doesNotMatch(abilitiesPhp + schemasPhp + executionPhp, /WooCommerce|Jetpack|Data Machine/i)

console.log("wordpress plugin public runtime abilities contract ok")
