import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"

const abilitiesPhp = await readFile("packages/wordpress-plugin/src/class-wp-codebox-abilities.php", "utf8")
const runtimeDescriptorsPhp = await readFile("packages/wordpress-plugin/src/class-wp-codebox-runtime-ability-descriptors.php", "utf8")
const schemasPhp = await readFile("packages/wordpress-plugin/src/trait-wp-codebox-abilities-schemas.php", "utf8")
const executionPhp = await readFile("packages/wordpress-plugin/src/trait-wp-codebox-abilities-execution.php", "utf8")
const fuzzSuiteRunnerPhp = await readFile("packages/wordpress-plugin/src/class-wp-codebox-fuzz-suite-runner.php", "utf8")

for (const ability of ["wp-codebox/run-wordpress-workload", "wp-codebox/run-fuzz-suite", "wp-codebox/run-runtime-package"]) {
  assert.match(abilitiesPhp, new RegExp(`wp_register_ability\\(\\s*'${ability}'`), `${ability} must be registered`)
  assert.match(runtimeDescriptorsPhp, new RegExp(`'canonical_ability'\\s*=>\\s*'${ability}'`), `${ability} must mark its canonical id`)
}

assert.match(runtimeDescriptorsPhp, /'execute_callback'\s*=>\s*array\(\s*WP_Codebox_Abilities::class,\s*'run_wordpress_workload'\s*\)/, "WordPress workload is implemented by the public ability")
assert.match(abilitiesPhp, /register_rest_route\(\s*'wp-codebox\/v1',\s*'\/runtime-task'[\s\S]{0,300}'callback'\s*=>\s*array\(\s*self::class,\s*'rest_runtime_task'\s*\)/, "Runtime task REST route must be Codebox-owned")
assert.match(abilitiesPhp, /function rest_runtime_task\( WP_REST_Request \$request \)/, "Runtime task REST route callback must be present")
assert.match(abilitiesPhp, /WP_Codebox_API::run_runtime_task\( \$input \)/, "Runtime task REST route must delegate through the public PHP facade")
assert.doesNotMatch(abilitiesPhp, /'wp-codebox\/run-wordpress-workload'[\s\S]{0,700}'safe_stub'\s*=>\s*true/, "WordPress workload is implemented and must not be marked as a safe stub")
assert.doesNotMatch(abilitiesPhp, /'wp-codebox\/run-fuzz-suite'[\s\S]{0,700}'safe_stub'\s*=>\s*true/, "Fuzz suite is implemented and must not be marked as a safe stub")

assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/wordpress-workload-run\/v1'/)
assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/wordpress-workload-run-result\/v1'/)
assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/fuzz-suite\/v1'/)
assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/fuzz-suite-result\/v1'/)
assert.match(schemasPhp, /private static function runtime_package_task_schema/)
assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/runtime-package-task\/v1'/)
assert.match(schemasPhp, /'required'\s*=>\s*array\( 'schema', 'package', 'workflow', 'input', 'artifact_declarations', 'required_artifacts' \)/)
assert.match(schemasPhp, /'required'\s*=>\s*array\( 'slug', 'source' \)/)
assert.match(schemasPhp, /'const'\s*=>\s*'wp-codebox\/runtime-package-result\/v1'/)
const runtimePackageRegistration = runtimeDescriptorsPhp.slice(runtimeDescriptorsPhp.indexOf("function run_runtime_package"))
assert.match(runtimePackageRegistration, /'input_schema'\s*=>\s*\$context\['runtime_package_task_schema'\]/)
assert.match(runtimePackageRegistration, /'output_schema'\s*=>\s*\$context\['runtime_package_result_schema'\]/)
assert.doesNotMatch(runtimePackageRegistration, /'runtime_package'\s*=>|'runtime-package-execution-input\/v1'/, "runtime package ability must advertise the canonical task contract, not legacy fields")
assert.match(schemasPhp, /'kind'\s*=>\s*array\( 'type' => 'string', 'enum' => array\( 'ability', 'command', 'http', 'rest', 'runtime', 'runtime-action' \) \)/)
assert.doesNotMatch(schemasPhp, /include_raw_browser_session/, "public browser session input schema must not expose raw browser session escape hatches")
assert.match(schemasPhp, /'required'\s*=>\s*array\( 'task', 'target_id' \)/, "runtime task requests must require explicit target_id")
const runtimeTaskSchema = schemasPhp.slice(schemasPhp.indexOf("private static function runtime_task_request_schema"), schemasPhp.indexOf("private static function runtime_task_result_schema"))
assert.doesNotMatch(runtimeTaskSchema, /'executor_id'\s*=>|\s'executor'\s*=>|\s'target'\s*=>/, "runtime task public schema must not advertise implicit target aliases")

assert.match(executionPhp, /function run_wordpress_workload\( array \$input \)/)
assert.match(executionPhp, /function run_fuzz_suite\( array \$input \)/)
assert.match(executionPhp, /function normalize_runtime_package_task_input\( array \$input \)/)
assert.match(executionPhp, /function legacy_runtime_package_task_input\( array \$input \)/)
assert.match(executionPhp, /function normalize_runtime_package_result\( array \$result, array \$task \)/)
assert.match(executionPhp, /unsafe_execution_fields/)
assert.match(executionPhp, /collect_unsafe_execution_fields/)
assert.match(executionPhp, /'code', 'php', 'php_code', 'raw_code', 'eval', 'shell'/)
assert.match(executionPhp, /array\( 'command' \)/)
assert.match(executionPhp, /new WP_Codebox_WordPress_Workload_Runner\(\)/)
assert.match(fuzzSuiteRunnerPhp, /execute_fuzz_suite_case/)
assert.doesNotMatch(executionPhp, /execute_fuzz_suite_case/, "Fuzz suite implementation must stay in WP_Codebox_Fuzz_Suite_Runner")
assert.match(fuzzSuiteRunnerPhp, /wordpress\.rest-request/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.http-request/)
assert.match(fuzzSuiteRunnerPhp, /fuzz_suite_runtime_action_step/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.wp-cli/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.browser-actions/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.browser-probe/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.editor-open/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.admin-page-load/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.frontend-page-load/)
assert.match(executionPhp, /function fuzz_suite_supported_runner_capabilities\(\)/)
assert.match(executionPhp, /function fuzz_suite_runtime_backed_runner_capabilities_contract/)
assert.match(executionPhp, /WP_Codebox_Fuzz_Suite_Runner::fuzz_suite_supported_runner_capabilities\(\)/)
assert.match(executionPhp, /WP_Codebox_Fuzz_Suite_Runner::fuzz_suite_runtime_backed_runner_capabilities_contract\( \$suite \)/)
assert.match(runtimeDescriptorsPhp, /Run safe PHP in-process WordPress fuzz-suite cases/)
assert.match(runtimeDescriptorsPhp, /Runtime-backed execution is available through the public wp-codebox CLI or TypeScript facade/)
assert.match(fuzzSuiteRunnerPhp, /runtime-action:db_operation/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.db-operation/)
assert.match(fuzzSuiteRunnerPhp, /executeWordPressFuzzSuite/)
assert.match(fuzzSuiteRunnerPhp, /wp-codebox run-fuzz-suite --runner-mode=runtime-backed/)
assert.match(fuzzSuiteRunnerPhp, /'ability_execution_mode'\s*=>\s*'php-in-process-only'/)
assert.match(fuzzSuiteRunnerPhp, /'supported_by_this_ability'\s*=>\s*false/)
assert.match(runtimeDescriptorsPhp, /'supported_runner_capabilities'\s*=>\s*\$context\['fuzz_suite_supported_runner_capabilities'\]/)
assert.match(runtimeDescriptorsPhp, /'runtime_backed_execution'\s*=>\s*\$context\['fuzz_suite_runtime_backed_execution_contract'\]/)
assert.match(fuzzSuiteRunnerPhp, /wordpress\.ensure-plugin-active/)
assert.match(fuzzSuiteRunnerPhp, /'commands'[\s\S]{0,900}wordpress\.ensure-plugin-active/)
assert.match(fuzzSuiteRunnerPhp, /'commands'[\s\S]{0,900}wordpress\.plugin-state/)
assert.match(fuzzSuiteRunnerPhp, /WP_CODEBOX_FUZZ_WORKLOAD_ROOT/)
assert.doesNotMatch(executionPhp, /wp_codebox_fuzz_suite_runner_unavailable/)

assert.doesNotMatch(abilitiesPhp + runtimeDescriptorsPhp + schemasPhp + executionPhp + fuzzSuiteRunnerPhp, /WooCommerce|Jetpack|Data Machine/i)

console.log("wordpress plugin public runtime abilities contract ok")
