<?php
/**
 * Browser ability descriptors.
 *
 * @package WPCodebox
 */

defined( 'ABSPATH' ) || exit;

/**
 * Provides browser runtime and artifact ability descriptors.
 */
final class WP_Codebox_Browser_Ability_Descriptors {

	/**
	 * @param array<string,mixed> $context Shared schemas assembled by WP_Codebox_Abilities.
	 * @return array<string,array<string,mixed>> Ability descriptors keyed by ability id.
	 */
	public static function descriptors( array $context ): array {
		$artifact_id_schema          = $context['artifact_id_schema'];
		$browser_contract_properties = $context['browser_contract_properties'];
		$browser_session_properties  = $context['browser_session_properties'];
		$browser_session_schema      = $context['browser_session_schema'];
		$inherit_schema              = $context['inherit_schema'];
		$session_input               = $context['session_input'];
		$sync_input_schema           = array(
			'type'       => 'object',
			'properties' => array(
				'contained_site'     => $context['browser_contained_site_schema'],
				'site_id'            => array( 'type' => 'string' ),
				'source_digest'      => array( 'type' => array( 'string', 'object' ) ),
				'input_hash'         => array( 'type' => 'string' ),
				'source'             => array( 'type' => 'object' ),
				'package'            => array( 'type' => 'object' ),
				'apply_plan'         => array( 'type' => 'object' ),
				'base_snapshot'      => array( 'type' => array( 'string', 'object' ) ),
				'allow_host_mutation' => array( 'type' => 'boolean' ),
			),
		);
		$sync_output_properties      = array(
			'success'   => array( 'type' => 'boolean' ),
			'schema'    => array( 'type' => 'string' ),
			'status'    => array( 'type' => 'string' ),
			'operation' => array( 'type' => 'string' ),
			'source'    => array( 'type' => 'object' ),
			'manifest'  => array( 'type' => 'object' ),
			'package'   => array( 'type' => 'object' ),
			'apply_plan' => array( 'type' => 'object' ),
			'validation' => array( 'type' => 'object' ),
			'validation_hash' => array( 'type' => 'string' ),
			'result'    => array( 'type' => 'object' ),
		);

		$descriptors = array(
			'wp-codebox/hydrate-browser-blueprint-ref'      => array(
				'label'               => 'Hydrate Browser Blueprint Ref',
				'description'         => 'Resolve a product-safe prepared browser blueprint ref into an executable contained WordPress runtime blueprint without requiring consumers to store blueprint files.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'ref'        => array( 'type' => 'string' ),
						'cache_key'  => array( 'type' => 'string' ),
						'input_hash' => array( 'type' => 'string' ),
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'       => array( 'type' => 'boolean' ),
						'schema'        => array( 'type' => 'string', 'const' => 'wp-codebox/browser-blueprint-hydration/v1' ),
						'blueprint_ref' => array( 'type' => 'object' ),
						'blueprint'     => array( 'type' => 'object' ),
						'provenance'    => array( 'type' => 'object' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'hydrate_browser_blueprint_ref' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/create-browser-playground-session'    => array(
				'label'               => 'Create Browser Sandbox Session',
				'description'         => 'Prepare a WP Codebox browser sandbox session without requiring the host to run the WP Codebox CLI or Node.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'goal' ),
					'properties' => $browser_session_properties,
				),
				'output_schema'       => $browser_session_schema,
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'create_browser_playground_session' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/create-browser-materializer-contract' => array(
				'label'               => 'Create Browser Materializer Contract',
				'description'         => 'Prepare the WP Codebox browser materialization contract for an already-created parent browser session. The executable runtime recipe is an implementation detail of the current backend.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'goal' ),
					'properties' => $browser_contract_properties,
				),
				'output_schema'       => $context['browser_materializer_contract_schema'],
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'create_browser_materializer_contract' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/create-browser-task-contract'         => array(
				'label'               => 'Create Browser Task Contract',
				'description'         => 'Prepare a product-facing multi-phase WP Codebox browser task contract with a primary session and optional materializer phases.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'goal' ),
					'properties' => $browser_contract_properties + array(
						'execute_phases' => array(
							'type'        => 'boolean',
							'description' => 'When true, explicitly execute host-side fanout and host-delegation phase requests after preparing the browser task contract. Defaults to false so contract creation remains side-effect-light.',
							'default'     => false,
						),
						'phases'         => array(
							'type'        => 'array',
							'description' => 'Optional named browser task phases. Generic phases may carry wp-codebox/agent-fanout-request/v1 or wp-codebox/host-delegation-request/v1 in request/input for explicit WP Codebox execution when execute_phases is true; materializer phases may override any primary session input through input.',
							'items'       => array(
								'type'       => 'object',
								'properties' => array(
									'name'     => array( 'type' => 'string' ),
									'kind'     => array( 'type' => 'string', 'enum' => $context['browser_task_phase_kinds'] ),
									'label'    => array( 'type' => 'string' ),
									'status'   => array( 'type' => 'string' ),
									'metadata' => array( 'type' => 'object' ),
									'request'  => array( 'type' => 'object' ),
									'input'    => array( 'type' => 'object' ),
								),
							),
						),
						'materializers'  => array(
							'type'        => 'array',
							'description' => 'Convenience list of materializer input overrides. Prefer phases for named multi-phase contracts.',
							'items'       => array( 'type' => 'object' ),
						),
					),
				),
				'output_schema'       => $context['browser_task_contract_schema'],
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'create_browser_task_contract' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/get-browser-contained-site-status'    => array(
				'label'               => 'Get Browser Contained Site Status',
				'description'         => 'Resolve a durable browser-contained site handle into explicit prepared-runtime recoverability or live/current/materialized availability without creating a new browser sandbox session.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'contained_site' => $context['browser_contained_site_schema'],
						'site_id'       => array( 'type' => 'string' ),
						'cache_key'     => array( 'type' => 'string' ),
						'source_digest' => array( 'type' => 'string' ),
						'input_hash'    => array( 'type' => 'string' ),
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'       => array( 'type' => 'boolean' ),
						'schema'        => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-status/v1' ),
						'site_id'       => array( 'type' => 'string' ),
						'open_mode'     => array( 'type' => 'string' ),
						'reuse_level'   => array( 'type' => 'string' ),
						'requires_materialization' => array( 'type' => 'boolean' ),
						'prepared_runtime_recoverable' => array( 'type' => 'boolean' ),
						'live'          => array( 'type' => 'boolean' ),
						'current'       => array( 'type' => 'boolean' ),
						'materialized'  => array( 'type' => 'boolean' ),
						'source_digest' => array( 'type' => 'object' ),
						'artifact_digest' => array( 'type' => 'object' ),
						'materialization_digest' => array( 'type' => 'object' ),
						'status'        => array( 'type' => 'string' ),
						'resolution'    => array( 'type' => 'object' ),
						'prepared_runtime' => array( 'type' => 'object' ),
						'blueprint_ref' => array( 'type' => 'object' ),
						'recovery'      => array( 'type' => 'object' ),
						'recovery_handle' => array( 'type' => 'string' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'get_browser_contained_site_status' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/preview-reuse-decision'              => array(
				'label'               => 'Preview Reuse Decision',
				'description'         => 'Return an explicit reuse/create/reload decision for a browser-contained preview site without creating a new browser sandbox session.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'contained_site' => $context['browser_contained_site_schema'],
						'site_id'       => array( 'type' => 'string' ),
						'cache_key'     => array( 'type' => 'string' ),
						'source_digest' => array( 'type' => 'string' ),
						'input_hash'    => array( 'type' => 'string' ),
						'policy'        => array( 'type' => 'object' ),
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'       => array( 'type' => 'boolean' ),
						'schema'        => array( 'type' => 'string', 'const' => 'wp-codebox/preview-reuse-decision/v1' ),
						'action'        => array( 'type' => 'string', 'enum' => array( 'reuse-current', 'hydrate-ref', 'create-new', 'reload-required' ) ),
						'decision'      => array( 'type' => 'string' ),
						'identity_key'  => array( 'type' => 'string' ),
						'reload_required' => array( 'type' => 'boolean' ),
						'site_id'       => array( 'type' => 'string' ),
						'open_mode'     => array( 'type' => 'string' ),
						'reuse_level'   => array( 'type' => 'string' ),
						'status'        => array( 'type' => 'string' ),
						'reason'        => array( 'type' => 'string' ),
						'resolution'    => array( 'type' => 'object' ),
						'status_result' => array( 'type' => 'object' ),
						'recovery'      => array( 'type' => 'object' ),
						'recovery_handle' => array( 'type' => 'string' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'preview_reuse_decision' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/open-browser-contained-site'          => array(
				'label'               => 'Open Browser Contained Site',
				'description'         => 'Resolve a browser-contained site handle into a product-safe open/reuse envelope with preview boot, lease, blueprint ref, and session identity when available.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'contained_site' => $context['browser_contained_site_schema'],
						'site_id'       => array( 'type' => 'string' ),
						'cache_key'     => array( 'type' => 'string' ),
						'source_digest' => array( 'type' => array( 'string', 'object' ), 'description' => '64-character source digest string, or an object with a value field.' ),
						'input_hash'    => array( 'type' => 'string' ),
						'runtime_profile' => array( 'type' => 'object' ),
						'recovery'      => array( 'type' => 'object' ),
						'preview_lease' => array( 'type' => 'object' ),
						'session_id'    => array( 'type' => 'string' ),
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'       => array( 'type' => 'boolean' ),
						'schema'        => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-open/v1' ),
						'site_id'       => array( 'type' => 'string' ),
						'open_mode'     => array( 'type' => 'string' ),
						'reuse_level'   => array( 'type' => 'string' ),
						'requires_materialization' => array( 'type' => 'boolean' ),
						'prepared_runtime_recoverable' => array( 'type' => 'boolean' ),
						'live'          => array( 'type' => 'boolean' ),
						'current'       => array( 'type' => 'boolean' ),
						'materialized'  => array( 'type' => 'boolean' ),
						'status'        => array( 'type' => 'string' ),
						'resolution'    => array( 'type' => 'object' ),
						'contained_site' => $context['browser_contained_site_schema'],
						'source_digest' => array( 'type' => 'object' ),
						'artifact_digest' => array( 'type' => 'object' ),
						'materialization_digest' => array( 'type' => 'object' ),
						'prepared_runtime' => array( 'type' => 'object' ),
						'blueprint_ref' => array( 'type' => 'object' ),
						'preview_boot'  => array( 'type' => 'object' ),
						'preview_lease' => array( 'type' => 'object' ),
						'preview_session' => array( 'type' => 'object' ),
						'session'       => array( 'type' => 'object' ),
						'recovery'      => array( 'type' => 'object' ),
						'recovery_handle' => array( 'type' => 'string' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'open_browser_contained_site' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/open-or-create-browser-contained-site' => array(
				'label'               => 'Open or Create Browser Contained Site',
				'description'         => 'Start a browser-contained preview with an explicit mode: open-only, open-or-create, or prepare-new.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'mode' ),
					'properties' => array_merge(
						$browser_session_properties,
						array(
							'mode'            => array(
								'type'        => 'string',
								'enum'        => array( 'open-only', 'open-or-create', 'prepare-new' ),
								'description' => 'Deterministic preview start mode. open-only never creates, open-or-create reuses when possible then creates, prepare-new always creates a fresh session.',
							),
							'contained_site'  => $context['browser_contained_site_schema'],
							'site_id'         => array( 'type' => 'string' ),
							'cache_key'       => array( 'type' => 'string' ),
							'source_digest'   => array( 'type' => array( 'string', 'object' ), 'description' => '64-character source digest string, or an object with a value field.' ),
							'input_hash'      => array( 'type' => 'string' ),
							'preview_lease'   => array( 'type' => 'object' ),
						)
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'       => array( 'type' => 'boolean' ),
						'schema'        => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-open-or-create/v1' ),
						'action'        => array( 'type' => 'string', 'enum' => array( 'opened', 'created', 'blocked', 'unavailable' ) ),
						'decision'      => array( 'type' => 'object' ),
						'identity_key'  => array( 'type' => 'string' ),
						'reload_required' => array( 'type' => 'boolean' ),
						'open'          => array( 'type' => 'object' ),
						'created'       => array( 'type' => 'object' ),
						'contained_site' => $context['browser_contained_site_schema'],
						'preview_boot'  => array( 'type' => 'object' ),
						'preview_lease' => array( 'type' => 'object' ),
						'preview_session' => array( 'type' => 'object' ),
						'session'       => array( 'type' => 'object' ),
						'error'         => array( 'type' => 'object' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'open_or_create_browser_contained_site' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/create-browser-contained-site-session' => array(
				'label'               => 'Create Browser Contained Site Session',
				'description'         => 'Create a browser-contained preview session and return a product-safe boot descriptor, preview lease, and startup diagnostics. Runtime boot internals remain available through legacy session envelopes and explicit hydration refs only.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'goal' ),
					'properties' => $browser_session_properties,
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'             => array( 'type' => 'boolean' ),
						'schema'              => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-session/v1' ),
						'action'              => array( 'type' => 'string' ),
						'contained_site'      => $context['browser_contained_site_schema'],
						'boot'                => array( 'type' => 'object' ),
						'preview_lease'       => array( 'type' => 'object' ),
						'startup_diagnostics' => array( 'type' => 'object' ),
						'session'             => array( 'type' => 'object' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'create_browser_contained_site_session' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/boot-browser-contained-site-session' => array(
				'label'               => 'Boot Browser Contained Site Session',
				'description'         => 'Open a reusable browser-contained preview and return the stable boot DTO with preview lease, blueprint ref, and diagnostics.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'contained_site' => $context['browser_contained_site_schema'],
						'site_id'       => array( 'type' => 'string' ),
						'cache_key'     => array( 'type' => 'string' ),
						'source_digest' => array( 'type' => array( 'string', 'object' ), 'description' => '64-character source digest string, or an object with a value field.' ),
						'input_hash'    => array( 'type' => 'string' ),
						'preview_lease' => array( 'type' => 'object' ),
						'session_id'    => array( 'type' => 'string' ),
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'             => array( 'type' => 'boolean' ),
						'schema'              => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-boot-result/v1' ),
						'action'              => array( 'type' => 'string' ),
						'boot'                => array( 'type' => 'object' ),
						'preview_lease'       => array( 'type' => 'object' ),
						'contained_site'      => $context['browser_contained_site_schema'],
						'startup_diagnostics' => array( 'type' => 'object' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'boot_browser_contained_site_session' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/preview-boot-ref' => array(
				'label'               => 'Get Preview Boot Ref',
				'description'         => 'Return the stable consumer preview boot ref DTO. The DTO exposes a blueprint hydration ref instead of inline runtime blueprint data.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'contained_site' => $context['browser_contained_site_schema'],
						'site_id'       => array( 'type' => 'string' ),
						'cache_key'     => array( 'type' => 'string' ),
						'source_digest' => array( 'type' => array( 'string', 'object' ), 'description' => '64-character source digest string, or an object with a value field.' ),
						'input_hash'    => array( 'type' => 'string' ),
						'preview_lease' => array( 'type' => 'object' ),
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'             => array( 'type' => 'boolean' ),
						'schema'              => array( 'type' => 'string', 'const' => 'wp-codebox/preview-boot-ref/v1' ),
						'boot'                => array( 'type' => 'object' ),
						'blueprint_ref'       => array( 'type' => 'object' ),
						'preview_lease'       => array( 'type' => 'object' ),
						'startup_diagnostics' => array( 'type' => 'object' ),
						'compatibility'       => array( 'type' => 'object' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'preview_boot_ref' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/destroy-browser-contained-site-session' => array(
				'label'               => 'Destroy Browser Contained Site Session',
				'description'         => 'Release a browser-contained preview session DTO and return a product-safe released preview lease envelope.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'contained_site' => $context['browser_contained_site_schema'],
						'site_id'       => array( 'type' => 'string' ),
						'source_digest' => array( 'type' => array( 'string', 'object' ) ),
						'preview_lease' => array( 'type' => 'object' ),
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'             => array( 'type' => 'boolean' ),
						'schema'              => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-destroy/v1' ),
						'action'              => array( 'type' => 'string' ),
						'contained_site'      => $context['browser_contained_site_schema'],
						'preview_lease'       => array( 'type' => 'object' ),
						'startup_diagnostics' => array( 'type' => 'object' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'destroy_browser_contained_site_session' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/snapshot-browser-contained-site' => array(
				'label'               => 'Snapshot Browser Contained Site',
				'description'         => 'Return a stable browser-contained site snapshot contract after validating the contained-site handle, session identity, scope, and source digest. This is a DTO boundary and does not mutate the host.',
				'category'            => 'wp-codebox',
				'input_schema'        => array( 'type' => 'object', 'properties' => array( 'contained_site' => $context['browser_contained_site_schema'], 'site_id' => array( 'type' => 'string' ), 'source_digest' => array( 'type' => array( 'string', 'object' ) ), 'input_hash' => array( 'type' => 'string' ), 'session_id' => array( 'type' => 'string' ), 'scope' => array( 'type' => 'string' ) ) ),
				'output_schema'       => array( 'type' => 'object', 'properties' => array( 'success' => array( 'type' => 'boolean' ), 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-snapshot/v1' ), 'contained_site' => $context['browser_contained_site_schema'], 'source_digest' => array( 'type' => 'object' ), 'session' => array( 'type' => 'object' ), 'status' => array( 'type' => 'object' ), 'snapshot' => array( 'type' => 'object' ), 'error' => array( 'type' => 'object' ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'snapshot_browser_contained_site' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/export-browser-contained-site' => array(
				'label'               => 'Export Browser Contained Site',
				'description'         => 'Return a stable replay export contract for a browser-contained site after source validation. This is preview-only and does not write to the host.',
				'category'            => 'wp-codebox',
				'input_schema'        => array( 'type' => 'object', 'properties' => array( 'contained_site' => $context['browser_contained_site_schema'], 'site_id' => array( 'type' => 'string' ), 'source_digest' => array( 'type' => array( 'string', 'object' ) ), 'input_hash' => array( 'type' => 'string' ), 'session_id' => array( 'type' => 'string' ), 'scope' => array( 'type' => 'string' ) ) ),
				'output_schema'       => array( 'type' => 'object', 'properties' => array( 'success' => array( 'type' => 'boolean' ), 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-export/v1' ), 'contained_site' => $context['browser_contained_site_schema'], 'source_digest' => array( 'type' => 'object' ), 'snapshot' => array( 'type' => 'object' ), 'export' => array( 'type' => 'object' ), 'error' => array( 'type' => 'object' ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'export_browser_contained_site' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/plan-browser-contained-site-apply' => array(
				'label'               => 'Plan Browser Contained Site Apply',
				'description'         => 'Build a browser-contained site apply plan. The default mode is preview-only and reports host_mutation=false.',
				'category'            => 'wp-codebox',
				'input_schema'        => array( 'type' => 'object', 'properties' => array( 'contained_site' => $context['browser_contained_site_schema'], 'site_id' => array( 'type' => 'string' ), 'source_digest' => array( 'type' => array( 'string', 'object' ) ), 'input_hash' => array( 'type' => 'string' ), 'session_id' => array( 'type' => 'string' ), 'scope' => array( 'type' => 'string' ), 'changes' => array( 'type' => 'array', 'items' => array( 'type' => 'object' ) ), 'apply' => array( 'type' => 'boolean' ), 'allow_host_mutation' => array( 'type' => 'boolean' ) ) ),
				'output_schema'       => array( 'type' => 'object', 'properties' => array( 'success' => array( 'type' => 'boolean' ), 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-apply-plan/v1' ), 'mode' => array( 'type' => 'string' ), 'host_mutation' => array( 'type' => 'boolean' ), 'contained_site' => $context['browser_contained_site_schema'], 'source_digest' => array( 'type' => 'object' ), 'plan' => array( 'type' => 'object' ), 'error' => array( 'type' => 'object' ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'plan_browser_contained_site_apply' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/apply-browser-contained-site-plan' => array(
				'label'               => 'Apply Browser Contained Site Plan',
				'description'         => 'Return a browser-contained apply result. Without explicit approved host mutation, this remains a preview result and does not mutate the host.',
				'category'            => 'wp-codebox',
				'input_schema'        => array( 'type' => 'object', 'properties' => array( 'contained_site' => $context['browser_contained_site_schema'], 'site_id' => array( 'type' => 'string' ), 'source_digest' => array( 'type' => array( 'string', 'object' ) ), 'input_hash' => array( 'type' => 'string' ), 'session_id' => array( 'type' => 'string' ), 'scope' => array( 'type' => 'string' ), 'plan' => array( 'type' => 'object' ), 'allow_host_mutation' => array( 'type' => 'boolean' ) ) ),
				'output_schema'       => array( 'type' => 'object', 'properties' => array( 'success' => array( 'type' => 'boolean' ), 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-apply-result/v1' ), 'mode' => array( 'type' => 'string' ), 'host_mutation' => array( 'type' => 'boolean' ), 'contained_site' => $context['browser_contained_site_schema'], 'source_digest' => array( 'type' => 'object' ), 'result' => array( 'type' => 'object' ), 'error' => array( 'type' => 'object' ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'apply_browser_contained_site_plan' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/browser-contained-site-sync-delegation' => array(
				'label'               => 'Browser Contained Site Sync Delegation',
				'description'         => 'Return the Codebox-owned contained-site sync delegation descriptor. Consumers use these Codebox routes and abilities instead of constructing backend sync routes directly.',
				'category'            => 'wp-codebox',
				'input_schema'        => $sync_input_schema,
				'output_schema'       => array( 'type' => 'object', 'properties' => array( 'success' => array( 'type' => 'boolean' ), 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-sync-delegation/v1' ), 'status' => array( 'type' => 'string' ), 'backend' => array( 'type' => 'object' ), 'routes' => array( 'type' => 'object' ), 'abilities' => array( 'type' => 'object' ), 'contained_site' => $context['browser_contained_site_schema'], 'source_digest' => array( 'type' => 'object' ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'browser_contained_site_sync_delegation' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/browser-contained-site-sync-source-connect' => array(
				'label'               => 'Browser Contained Site Sync Source Connect',
				'description'         => 'Connect a browser-contained site sync source through the Codebox public facade.',
				'category'            => 'wp-codebox',
				'input_schema'        => $sync_input_schema,
				'output_schema'       => array( 'type' => 'object', 'properties' => array_merge( $sync_output_properties, array( 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-sync-source/v1' ) ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'browser_contained_site_sync_source_connect' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/browser-contained-site-sync-manifest' => array(
				'label'               => 'Browser Contained Site Sync Manifest',
				'description'         => 'Return a Codebox contained-site sync manifest DTO, delegating to the installed backend when available.',
				'category'            => 'wp-codebox',
				'input_schema'        => $sync_input_schema,
				'output_schema'       => array( 'type' => 'object', 'properties' => array_merge( $sync_output_properties, array( 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-sync-manifest/v1' ) ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'browser_contained_site_sync_manifest' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/browser-contained-site-sync-export' => array(
				'label'               => 'Browser Contained Site Sync Export',
				'description'         => 'Return a Codebox contained-site sync export DTO, delegating to the installed backend when available.',
				'category'            => 'wp-codebox',
				'input_schema'        => $sync_input_schema,
				'output_schema'       => array( 'type' => 'object', 'properties' => array_merge( $sync_output_properties, array( 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-sync-export/v1' ) ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'browser_contained_site_sync_export' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/browser-contained-site-sync-apply-plan-generate' => array(
				'label'               => 'Browser Contained Site Sync Apply Plan Generate',
				'description'         => 'Generate a Codebox contained-site sync apply plan. The fallback plan is preview-only and reports no host mutation.',
				'category'            => 'wp-codebox',
				'input_schema'        => $sync_input_schema,
				'output_schema'       => array( 'type' => 'object', 'properties' => array_merge( $sync_output_properties, array( 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-sync-apply-plan/v1' ) ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'browser_contained_site_sync_apply_plan_generate' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/browser-contained-site-sync-apply-plan-validate' => array(
				'label'               => 'Browser Contained Site Sync Apply Plan Validate',
				'description'         => 'Validate a Codebox contained-site sync apply plan through the public facade.',
				'category'            => 'wp-codebox',
				'input_schema'        => $sync_input_schema,
				'output_schema'       => array( 'type' => 'object', 'properties' => array_merge( $sync_output_properties, array( 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-sync-validation/v1' ) ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'browser_contained_site_sync_apply_plan_validate' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/browser-contained-site-sync-apply' => array(
				'label'               => 'Browser Contained Site Sync Apply',
				'description'         => 'Apply a Codebox contained-site sync plan through the public facade. Without explicit approved host mutation this remains a preview result.',
				'category'            => 'wp-codebox',
				'input_schema'        => $sync_input_schema,
				'output_schema'       => array( 'type' => 'object', 'properties' => array_merge( $sync_output_properties, array( 'schema' => array( 'type' => 'string', 'const' => 'wp-codebox/browser-contained-site-sync-apply-result/v1' ) ) ) ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'browser_contained_site_sync_apply' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_create_browser_playground_session' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/browser-connector-request'            => array(
				'label'               => 'Run Browser Connector Request',
				'description'         => 'Resolve connector credentials server-side and dispatch a generic browser connector request with secrets kept in the connector runtime.',
				'category'            => 'wp-codebox',
				'input_schema'        => $context['browser_connector_request_schema'],
				'output_schema'       => $context['browser_connector_response_schema'],
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'browser_connector_request' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_request_browser_connector' ),
				'meta'                => array( 'show_in_rest' => true, 'canonical_ability' => 'wp-codebox/browser-connector-request' ),
			),
			'wp-codebox/execute-browser-provider-request'     => array(
				'label'               => 'Execute Browser Provider Request',
				'description'         => 'Legacy provider-adapter path for connector-scoped browser provider requests. Prefer wp-codebox/browser-connector-request for new connector-scoped browser calls unless the provider-adapter response shape is required.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'operation', 'request', 'inherit' ),
					'properties' => array(
						'operation'          => array(
							'type'        => 'string',
							'description' => 'Generic provider operation id, for example chat.completions. WP Codebox treats this as opaque adapter input.',
						),
						'provider'           => array( 'type' => 'string' ),
						'model'              => array( 'type' => 'string' ),
						'connector'          => array(
							'type'        => 'string',
							'description' => 'Optional connector name to select from the resolved inheritance connector set. Defaults to the first resolved connector.',
						),
						'inherit'            => $inherit_schema,
						'request'            => array(
							'type'        => 'object',
							'description' => 'Generic provider request payload. Secret-like fields are redacted before adapter/audit envelopes are returned.',
						),
						'sandbox_session_id' => $session_input['sandbox_session_id'],
						'session_id'         => array( 'type' => 'string' ),
						'caller_session_id'  => array( 'type' => 'string' ),
						'job_id'             => array( 'type' => 'string' ),
						'orchestrator'       => $session_input['orchestrator'],
						'authorization'      => $context['browser_connector_authorization_schema'],
					),
				),
				'output_schema'       => array(
					'type'       => 'object',
					'properties' => array(
						'success'   => array( 'type' => 'boolean' ),
						'schema'    => array( 'type' => 'string', 'const' => 'wp-codebox/browser-provider-adapter-response/v1' ),
						'operation' => array( 'type' => 'string' ),
						'provider'  => array( 'type' => 'string' ),
						'model'     => array( 'type' => 'string' ),
						'connector' => array( 'type' => 'object' ),
						'response'  => array( 'type' => 'object' ),
						'audit'     => array( 'type' => 'object' ),
					),
				),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'execute_browser_provider_request' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_request_browser_connector' ),
				'meta'                => array( 'show_in_rest' => true, 'preferred_ability' => 'wp-codebox/browser-connector-request' ),
			),
			'wp-codebox/list-artifacts'                       => array(
				'label'               => 'List WP Codebox Artifacts',
				'description'         => 'List artifact bundles under the configured WP Codebox artifact root.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'artifacts_path' => $artifact_id_schema['artifacts_path'],
					),
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'list_artifacts' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_run_agent_task' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/get-artifact'                        => array(
				'label'               => 'Get WP Codebox Artifact',
				'description'         => 'Read one WP Codebox artifact bundle by id.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'artifact_id' ),
					'properties' => $artifact_id_schema,
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'get_artifact' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_run_agent_task' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/inspect-artifact'                    => array(
				'label'               => 'Inspect WP Codebox Artifact',
				'description'         => 'Read one WP Codebox artifact bundle by id and return Codebox-owned verification details without requiring consumers to inspect artifact directory internals.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'artifact_id' ),
					'properties' => $artifact_id_schema,
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'inspect_artifact' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_run_agent_task' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/discard-artifact'                    => array(
				'label'               => 'Discard WP Codebox Artifact',
				'description'         => 'Delete one WP Codebox artifact bundle from the configured artifact root.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'artifact_id' ),
					'properties' => $artifact_id_schema,
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'discard_artifact' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_run_agent_task' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/normalize-browser-artifact-bundle'   => array(
				'label'               => 'Normalize Browser Artifact Bundle',
				'description'         => 'Normalize and verify a caller-owned browser artifact bundle without interpreting product-specific roles or metadata.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'schema_id', 'entrypoint', 'files' ),
					'properties' => array(
						'schema_id'  => array(
							'type'        => 'string',
							'description' => 'Caller-owned schema id for the product artifact contract being normalized.',
						),
						'root'       => array(
							'type'        => 'string',
							'description' => 'Optional safe relative artifact root applied to entrypoint and file paths.',
						),
						'entrypoint' => array(
							'type'        => 'string',
							'description' => 'Safe relative entrypoint path that must exist in the normalized files.',
						),
						'roles'      => array(
							'type'        => 'object',
							'description' => 'Opaque caller role metadata preserved without product-specific interpretation.',
						),
						'provenance' => array(
							'type'        => 'object',
							'description' => 'Opaque caller provenance preserved on the normalized bundle.',
						),
						'metadata'   => array(
							'type'        => 'object',
							'description' => 'Opaque caller metadata preserved on the normalized bundle.',
						),
						'files'      => array(
							'type'        => 'array',
							'description' => 'Browser-produced artifact files to normalize.',
							'items'       => array(
								'type'       => 'object',
								'required'   => array( 'path' ),
								'properties' => array(
									'path'           => array( 'type' => 'string' ),
									'content'        => array( 'type' => 'string' ),
									'content_base64' => array( 'type' => 'string' ),
									'encoding'       => array( 'type' => 'string', 'enum' => array( 'utf-8', 'base64' ) ),
									'mime_type'      => array( 'type' => 'string' ),
									'kind'           => array( 'type' => 'string' ),
									'roles'          => array( 'type' => 'array', 'items' => array( 'type' => 'string' ) ),
								),
							),
						),
					),
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'normalize_browser_artifact_bundle' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_run_agent_task' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/persist-browser-artifact'            => array(
				'label'               => 'Persist Browser Artifact',
				'description'         => 'Persist browser-produced files from a disposable browser sandbox session as a canonical WP Codebox artifact bundle.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'required'   => array( 'files' ),
					'properties' => array(
						'artifacts_path'   => $artifact_id_schema['artifacts_path'],
						'authorization'    => $context['trusted_artifact_authorization_schema'],
						'session_id'       => array(
							'type'        => 'string',
							'description' => 'Optional browser sandbox session id that produced the artifact files.',
						),
						'session'          => array(
							'type'        => 'object',
							'description' => 'Optional browser session metadata to preserve in artifact runtime provenance.',
						),
						'provenance'       => array(
							'type'        => 'object',
							'description' => 'Opaque caller provenance describing who requested the browser run and what produced these files.',
						),
						'caller'           => array(
							'type'        => 'object',
							'description' => 'Opaque caller-owned schema and metadata to preserve in the canonical artifact bundle.',
						),
						'caller_schema'    => array(
							'type'        => 'string',
							'description' => 'Optional caller schema URI or id preserved under metadata.caller.schema.',
						),
						'caller_schema_id' => array(
							'type'        => 'string',
							'description' => 'Optional caller schema id preserved under metadata.caller.schemaId.',
						),
						'caller_kind'      => array(
							'type'        => 'string',
							'description' => 'Optional caller artifact kind preserved under metadata.caller.kind.',
						),
						'caller_metadata'  => array(
							'type'        => 'object',
							'description' => 'Opaque caller-owned artifact bundle metadata preserved under metadata.caller.metadata.',
						),
						'materialization'  => array(
							'type'        => 'object',
							'description' => 'Opaque caller materialization metadata preserved under metadata.caller.materialization.',
						),
						'review_hints'     => array(
							'type'        => 'object',
							'description' => 'Optional caller review hints preserved in bundle metadata and review metadata.',
						),
						'apply_target'     => array(
							'type'        => 'object',
							'description' => 'Opaque caller apply target metadata preserved under metadata.caller.applyTarget.',
						),
						'files'            => array(
							'type'        => 'array',
							'description' => 'Browser-produced artifact files to store under files/browser/ in a canonical WP Codebox artifact bundle.',
							'items'       => array(
								'type'       => 'object',
								'required'   => array( 'path' ),
								'properties' => array(
									'path'           => array( 'type' => 'string' ),
									'content'        => array( 'type' => 'string' ),
									'content_base64' => array( 'type' => 'string' ),
									'encoding'       => array( 'type' => 'string', 'enum' => array( 'utf-8', 'base64' ) ),
									'mime_type'      => array( 'type' => 'string' ),
									'kind'           => array( 'type' => 'string' ),
								),
							),
						),
					),
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'persist_browser_artifact' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_persist_browser_artifact' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/import-artifact-bundle'               => array(
				'label'               => 'Import Artifact Bundle',
				'description'         => 'Verify and import an existing WP Codebox artifact bundle into the configured artifact store, returning a stable artifact result envelope.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'artifacts_path'       => $artifact_id_schema['artifacts_path'],
						'source_bundle_path'   => array( 'type' => 'string' ),
						'source_manifest_path' => array( 'type' => 'string' ),
						'expected_artifact_id' => array( 'type' => 'string' ),
						'expected_content_digest' => array( 'type' => 'string' ),
						'replace'              => array( 'type' => 'boolean' ),
						'authorization'        => $context['trusted_artifact_authorization_schema'],
						'metadata'             => array( 'type' => 'object' ),
					),
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'import_artifact_bundle' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_import_artifact_bundle' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
			'wp-codebox/reimport-artifact-bundle'             => array(
				'label'               => 'Reimport Artifact Bundle',
				'description'         => 'Re-run artifact bundle import semantics for a revised or restored artifact bundle and return a stable artifact result envelope.',
				'category'            => 'wp-codebox',
				'input_schema'        => array(
					'type'       => 'object',
					'properties' => array(
						'artifacts_path'       => $artifact_id_schema['artifacts_path'],
						'artifact_id'          => $artifact_id_schema['artifact_id'],
						'artifact_ref'         => array( 'type' => 'object' ),
						'artifact_result'      => array( 'type' => 'object' ),
						'source_bundle_path'   => array( 'type' => 'string' ),
						'source_manifest_path' => array( 'type' => 'string' ),
						'expected_content_digest' => array( 'type' => 'string' ),
						'replace'              => array( 'type' => 'boolean' ),
						'authorization'        => $context['trusted_artifact_authorization_schema'],
						'metadata'             => array( 'type' => 'object' ),
					),
				),
				'output_schema'       => array( 'type' => 'object' ),
				'execute_callback'    => array( WP_Codebox_Abilities::class, 'reimport_artifact_bundle' ),
				'permission_callback' => array( WP_Codebox_Abilities::class, 'can_import_artifact_bundle' ),
				'meta'                => array( 'show_in_rest' => true ),
			),
		);

		return $descriptors;
	}
}
